[package]
name = "gen-multi-skinned-assets"
version = "0.1.0"
edition = "2021"
description = "Generate assets for multi-skinned-rom example"

[dependencies]
zx-common = { path = "../../zx-common", default-features = false }

[dev-dependencies]
tempfile = { workspace = true }
