[package]
name = "proc-gen-mode2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
proc-gen-common = { path = "../proc-gen-common" }

[profile.release]
opt-level = "s"
lto = true
