[package]
name = "level-loader"
version = "0.1.0"
edition = "2021"
description = "Demonstrates loading custom level data from a data pack"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
lto = true
