[package]
name = "mode3-inspector"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libm = "0.2"
examples-common = { path = "../examples-common" }

[profile.release]
opt-level = "s"
lto = true
