[env]
# or debug, trace, warn, error
RUST_LOG = "core=warn,nethercore_zx=info"           
RUST_BACKTRACE = "1"

[alias]
xtask = "run --package xtask --"
ba = "build --workspace"
dev = "build --release -p nethercore-zx -p nether-cli"
