[package]
name = "blinn-phong"
version = "0.1.0"
edition = "2021"

[dependencies]
libm = "0.2"
emberware-examples-common = { path = "../common" }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
