[package]
name = "gen-basic-assets"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
clap = { version = "4.0", features = ["derive"] }
nether-export = { path = "../nether-export" }
hound = "3.5"
