[package]
name = "asset-gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "asset-gen"
path = "src/main.rs"

[dependencies]
proc-gen = { path = "../proc-gen" }
clap = { version = "4", features = ["derive"] }
