# Asset manifest for asset-test example
#
# Uses shared assets from examples/assets/ folder

[output]
dir = "../../assets/"

[codegen]
rust = "src/assets.rs"

[meshes]
cube = "../../assets/cube.obj"

[textures]
checkerboard = "../../assets/checkerboard.png"
